### ISSUE TITLE
How the hell do I use this?

### ISSUE THREAD

**Issue by vertex-235** [alexdieu/TIGIF#1]
After downloading the repo and extracting it, I put the `test.mp4` into the imgs folder and ran `convimg.exe` and nothing happened. It didn't spit it out to the 8xp-progs folder. How am I supposed to use this? The readme was quite vague and took me a while to figure out this much

**Comment by Eph777** [comment]
did you find a way to use it or to convert mp4 to 8xp with an other program ?

**Comment by Eph777** [comment]
@vertex-235

**Comment by alexdieu** [comment]
@Eph777 just run convert.py with python 3. Normally it should work. If it wont please describe me your problem

**Comment by Eph777** [comment]
hi @alexdieu !
thank you for the replay
here is the error message i had when i ran convert.py 

makefile:6: /include/.makefile: No such file or directory
makeVpy.exe: *** No rule to make target `/include/.makefile'.  Stop.
Traceback (most recent call last):
  File "D:\Dossiers\Bureau\TIGIF-main\convert.py", line 175, in <module>
    subprocess.check_call(['makeVpy.exe'], cwd=workdri)
  File "C:\Users\ephra\anaconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['makeVpy.exe']' returned non-zero exit status 2.

**Comment by Eph777** [comment]
the program stops at "[INFO] BUIDLING ..." and it shows this error

**Comment by Eph777** [comment]
I think it's the makeVpy.exe which doesn't work and you said in the document that it is out of use, but i don't know how to replace it by one which is usable

**Comment by alexdieu** [comment]
@Eph777 I've updated the software. Please forward me any other errors you encounter running it.

**Comment by Eph777** [comment]
i misunderstand, it displays me the same error message : 

makefile:6: /include/.makefile: No such file or directory
make2.exe: *** No rule to make target `/include/.makefile'.  Stop.
Traceback (most recent call last):
  File "D:\Dossiers\Bureau\TIGIF-main\convert.py", line 175, in <module>
    subprocess.check_call(['make2.exe'], cwd=workdri)
  File "C:\Users\ephra\anaconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make2.exe']' returned non-zero exit status 2.
